# Generated by Django 4.1.2 on 2022-10-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='files/front/upload/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.category')),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='PhotoDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.language')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.photo')),
            ],
            options={
                'verbose_name_plural': 'Photos descriptions',
                'db_table': 'photo_description',
            },
        ),
        migrations.CreateModel(
            name='Categorydescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.category')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.language')),
            ],
            options={
                'verbose_name_plural': 'Categories descriptions',
                'db_table': 'category_description',
            },
        ),
    ]
