# Generated by Django 4.1.2 on 2022-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0002_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
