# Generated by Django 4.1.2 on 2022-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='files/front/upload/% Y/% m/% d/'),
        ),
    ]
