# Generated by Django 4.1.2 on 2022-10-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0005_remove_categorydescription_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydescription',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.language'),
        ),
        migrations.AlterField(
            model_name='categorydescription',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.category'),
        ),
    ]
