# Generated by Django 4.1.2 on 2022-11-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0005_remove_photodescription_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='files/front/upload/images'),
        ),
    ]
