# Generated by Django 4.1.2 on 2022-11-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
