# Generated by Django 4.1.2 on 2022-12-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0010_alter_photo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genocide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Genocides',
                'db_table': 'genocide',
            },
        ),
        migrations.CreateModel(
            name='GenocideDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('genocide_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.genocide')),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='putinwarcrimes.language')),
            ],
            options={
                'verbose_name_plural': 'Genocide descriptions',
                'db_table': 'genocide_desc',
            },
        ),
    ]
