# Generated by Django 4.1.2 on 2022-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0011_genocide_genocidedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='genocidedescription',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
