# Generated by Django 4.1.2 on 2022-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0012_genocidedescription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genocidedescription',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
