# Generated by Django 4.1.2 on 2022-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0013_genocidedescription_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genocidedescription',
            name='latest',
        ),
        migrations.AddField(
            model_name='genocide',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
