# Generated by Django 4.1.2 on 2022-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0014_remove_genocidedescription_latest_genocide_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genocidedescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='genocidedescription',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
