# Generated by Django 4.1.2 on 2022-12-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0015_alter_genocidedescription_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genocidedescription',
            name='name',
        ),
    ]
