# Generated by Django 4.1.2 on 2022-12-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putinwarcrimes', '0016_remove_genocidedescription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genocide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
